"use client";

import { useEffect, useState } from "react";
import type { BuildComponent } from "@/components/OrgChart";

/**
 * `build.json`, which the CLI DERIVES from the repository — module imports, test
 * coverage, the golden file, the case set, and whether FITTED_BETA_MEASURED is
 * still False.
 *
 * It is fetched rather than imported so it stays a runtime artifact: the file is
 * regenerated by `forecast status --json` and staged next to the export, and
 * baking it into the bundle at build time would mean the status board reports
 * whatever was true when the UI was last compiled. That is exactly the failure
 * mode a derived status board exists to prevent.
 *
 * Two screens read it, so the hook lives here rather than being written twice
 * and drifting.
 */
export interface BuildGate {
  id: string;
  label: string;
  passed: boolean;
  detail: string;
  blocks: string;
}

export interface BuildPayload {
  components: BuildComponent[];
  gates: BuildGate[];
  totals: {
    components: number;
    built: number;
    partial: number;
    missing: number;
    tests: number;
    gates_passed: number;
    gates_total: number;
  };
}

export function useBuild(): BuildPayload | null {
  const [build, setBuild] = useState<BuildPayload | null>(null);
  useEffect(() => {
    void fetch("/build.json")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => data && setBuild(data as BuildPayload))
      // Absent build.json is a legitimate state — the UI runs before anything
      // has been staged — so it is an empty overlay, not an error.
      .catch(() => setBuild(null));
  }, []);
  return build;
}
