// GENERATED by `make types` from src/forecaster/schemas.py
// Do not edit. Change the pydantic model and regenerate.
//
// The pipeline writes out/results.json and out/events.ndjson; these are the
// shapes it writes. If the UI compiles, the two processes agree.

// ---- enums ----------------------------------------------------
export type Basis = "gaap" | "non_gaap";
export type SourceKind = "filing_index" | "8k" | "10q" | "10k" | "company_site" | "transcript" | "news" | "xbrl" | "consensus" | "macro" | "peer" | "sponsor" | "derived";
export type LensName = "mechanical" | "guidance" | "drivers" | "margins" | "forensics" | "peer_read" | "macro" | "market" | "demand";
export type LambdaPreset = "shrink" | "barbell" | "calibrated";
export type EventType = "run_start" | "node_start" | "node_done" | "node_failed" | "claim_added" | "run_done";

// ---- nested types ---------------------------------------------
// ---- models ---------------------------------------------------
/**
 * Where a number came from, and when it became knowable.
 * 
 * `as_of` is what makes point-in-time backtesting possible: it is the date the
 * fact was *filed or published*, not the period it describes.
 */
export interface Source {
  kind: SourceKind;
  uri: string;
  as_of: string;
  accession?: string | null;
  page_or_section?: string | null;
}

/**
 * A single fact, with provenance. The atom of the evidence store.
 * 
 * Deliberately impossible to construct without a source. `verbatim_quote` is
 * verified against the source document by `v1_reconcile.verify_citations` —
 * a quote that does not appear in its source drops the whole lens.
 */
export interface Claim {
  id: string;
  label: string;
  value?: number | string | null;
  unit?: string | null;
  period?: string | null;
  source: Source;
  verbatim_quote: string;
  confidence?: number;
}

/**
 * The Street's view, plus the metadata that tells you how much to trust it.
 * 
 * `n_analysts`, `dispersion` and `days_since_last_revision` are the inputs to
 * lambda. They matter more than the estimate itself.
 */
export interface Consensus {
  eps: number;
  revenue?: number | null;
  basis?: Basis;
  n_analysts?: number | null;
  eps_high?: number | null;
  eps_low?: number | null;
  days_since_last_revision?: number | null;
  revisions_up_30d?: number | null;
  revisions_down_30d?: number | null;
  as_of: string;
}

/**
 * What management told the Street to expect, at the last earnings call.
 * 
 * 58-63% of guiding companies guide *negative*. This is a floor-setting
 * exercise, not a forecast — which is why `landing_cdf` below matters more
 * than the range itself.
 */
export interface Guidance {
  metric: "eps" | "revenue";
  period: string;
  low?: number | null;
  high?: number | null;
  point?: number | null;
  basis?: Basis;
  constant_currency?: boolean;
  claim_id: string;
}

/**
 * Where this company historically lands *inside its own guided range*.
 * 
 * Everyone reads the guidance. Almost nobody builds this. Some companies hit
 * the midpoint like clockwork; some habitually clear the top end. Expressed as
 * a position in [0, 1] where 0 = low end, 1 = high end, >1 = beat the range.
 */
export interface LandingDistribution {
  ticker: string;
  n_quarters: number;
  positions: number[];
  median_position: number;
  /** Empirical-Bayes shrunk toward the sector median. With n~8 the raw statistic is mostly noise; this is the one to use. */
  shrunk_position: number;
}

/**
 * One lens's independent view. Lenses never see each other's output —
 * if they do they converge, and converging is how you rebuild consensus.
 */
export interface LensOutput {
  lens: LensName;
  eps?: number | null;
  revenue?: number | null;
  basis?: Basis;
  reasoning: string;
  /** Every claim this lens relied on. A lens that cites nothing is dropped by the reconciler. */
  claim_ids: string[];
  confidence: number;
  revenue_growth?: number | null;
  gross_margin?: number | null;
  opex_pct_revenue?: number | null;
  tax_rate?: number | null;
  reconciled?: boolean | null;
  reconcile_errors?: string[];
  thesis?: string | null;
  counterargument?: string | null;
  run_index?: number;
  model_used?: string | null;
  input_tokens?: number;
  output_tokens?: number;
  latency_ms?: number;
}

/**
 * The judge's output, and the system's internal currency.
 * 
 * A distribution is a strict superset of a point forecast: you can emit a
 * median for MAE, a mean for MSE, quantiles for CRPS, or a direction for a
 * win-rate metric. Building this once makes the scoring rule a config value
 * rather than a design input.
 */
export interface Distribution {
  median: number;
  mean: number;
  /** Keys are quantile levels as strings, e.g. '0.1', '0.5', '0.9'. */
  quantiles: Record<string, number>;
  stdev?: number | null;
  calibrated?: boolean;
}

/**
 * How far off the Street we go, and why. This is the thesis, made explicit.
 * 
 * Everything upstream of here forecasts. This decides how much to trust that
 * forecast against sixty-one analysts. Keeping it structurally separate is
 * the point.
 */
export interface LambdaDecision {
  preset: LambdaPreset;
  value: number;
  n_analysts?: number | null;
  dispersion?: number | null;
  consensus_stale?: boolean;
  /** Spread across lens estimates. High disagreement means our own evidence is weak — shrink regardless of what the meta-layer says. */
  internal_disagreement: number;
  /** M&A, accounting change, 53rd week, withdrawn guidance. When set, lambda collapses — historical priors do not apply. */
  comparability_flag?: string | null;
  rationale: string;
}

/**
 * What gets submitted, and what the UI renders.
 * 
 * Carries *both* bases. Which one is scored is the single largest unknown
 * going into the day, and modelling both turns it into a flag.
 */
export interface Forecast {
  ticker: string;
  period: string;
  as_of: string;
  eps_non_gaap: number;
  eps_gaap?: number | null;
  revenue?: number | null;
  distribution: Distribution;
  consensus: Consensus;
  lambda_decision: LambdaDecision;
  lenses: LensOutput[];
  /** Lens name -> why it was dropped. Surfaced in the UI, never silently swallowed. */
  droppee_lenses?: Record<string, string>;
  /** consensus * (1 + shrunk company surprise). Every chart shows this. If we cannot beat it, lambda should have been zero. */
  baseline_eps: number;
  total_cost_usd?: number;
  total_input_tokens?: number;
  total_output_tokens?: number;
  wall_clock_ms?: number;
  /** Our deviation from the Street, as a fraction. A computed field rather than a plain property so it is serialised into `out/results.json` and appears in the generated TypeScript. A bare `@property` exists only in Python, which means the UI would have to recompute it — and a number recomputed in two places is a number that eventually disagrees with itself. */
  surprise_vs_consensus: number;
}

/**
 * One line of out/events.ndjson. The live architecture view is driven
 * entirely by this stream — which is also why replay mode is free.
 */
export interface Event {
  seq: number;
  type: EventType;
  node?: string | null;
  ts_ms: number;
  payload?: Record<string, unknown>;
}

// ---- convenience ----------------------------------------------
/** One line of out/events.ndjson. */
export type EventLine = Event;
/** The whole of out/results.json. */
export type Results = Forecast;
