"""pydantic schemas -> ui/lib/types.ts. Run via `make types`.

Stops the pipeline and the frontend drifting. They otherwise will, and you find
out at 16:00 on the day when a field renamed three days earlier silently renders
as undefined.

This emits real TypeScript interfaces, not the JSON Schema as a type literal.
The distinction matters: `export type Consensus = {"properties": ...}` is valid
TypeScript and completely useless — the UI needs `consensus.eps` to typecheck,
not a description of the schema that describes it.

Deliberately a small local emitter rather than a json-schema-to-typescript
dependency: `make types` then needs no node toolchain, so it runs in CI and in
the container, and the output is stable enough to diff in a golden test.
"""

from __future__ import annotations

import sys
from typing import Any

from forecaster import schemas

# Order matters only for readability — TypeScript hoists type declarations.
MODELS = [
    schemas.Source,
    schemas.Claim,
    schemas.Consensus,
    schemas.Guidance,
    schemas.LandingDistribution,
    schemas.LensOutput,
    schemas.Distribution,
    schemas.LambdaDecision,
    schemas.Forecast,
    schemas.Event,
]

ENUMS = [
    schemas.Basis,
    schemas.SourceKind,
    schemas.LensName,
    schemas.LambdaPreset,
    schemas.EventType,
]

HEADER = """// GENERATED by `make types` from src/forecaster/schemas.py
// Do not edit. Change the pydantic model and regenerate.
//
// The pipeline writes out/results.json and out/events.ndjson; these are the
// shapes it writes. If the UI compiles, the two processes agree.
"""


def _ref_name(ref: str) -> str:
    """'#/$defs/Source' -> 'Source'."""
    return ref.rsplit("/", 1)[-1]


def ts_type(node: dict[str, Any]) -> str:
    """One JSON Schema node -> one TypeScript type expression."""
    if "$ref" in node:
        return _ref_name(node["$ref"])

    # pydantic renders `X | None` as anyOf[X, null]. Collapse it back to a union
    # rather than emitting `| null` twice — optionality is handled at the field.
    if "anyOf" in node:
        parts = [ts_type(sub) for sub in node["anyOf"] if sub.get("type") != "null"]
        if any(sub.get("type") == "null" for sub in node["anyOf"]):
            parts.append("null")
        # dedupe while preserving order
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen) or "unknown"

    if "const" in node:
        return f'"{node["const"]}"'

    if "enum" in node:
        return " | ".join(f'"{v}"' for v in node["enum"])

    kind = node.get("type")
    if kind == "array":
        items = node.get("items")
        return f"{ts_type(items)}[]" if items else "unknown[]"
    if kind == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {ts_type(extra)}>"
        return "Record<string, unknown>"
    if kind == "string":
        return "string"
    if kind in ("number", "integer"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    return "unknown"


def _is_optional(node: dict[str, Any]) -> bool:
    """True when the field can legitimately be absent or null in the JSON."""
    if "$ref" in node:
        return False
    return any(sub.get("type") == "null" for sub in node.get("anyOf", []))


def emit_interface(name: str, schema: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    if desc := schema.get("description"):
        lines.append("/**")
        lines.extend(f" * {line}" for line in desc.strip().splitlines())
        lines.append(" */")
    lines.append(f"export interface {name} {{")

    required = set(schema.get("required", []))
    for field, node in (schema.get("properties") or {}).items():
        if field_desc := node.get("description"):
            flat = " ".join(field_desc.split())
            lines.append(f"  /** {flat} */")
        # A field with a default is never absent from pydantic's own JSON dump,
        # but marking it optional keeps hand-written fixtures usable in the UI.
        optional = "" if field in required and not _is_optional(node) else "?"
        lines.append(f"  {field}{optional}: {ts_type(node)};")

    lines.append("}")
    return lines


def build() -> str:
    out: list[str] = [HEADER]

    out.append("// ---- enums ----------------------------------------------------")
    for enum in ENUMS:
        members = " | ".join(f'"{m.value}"' for m in enum)
        out.append(f"export type {enum.__name__} = {members};")
    out.append("")

    # Collect every $def across all models once, so shared nested types are
    # emitted a single time rather than per-model.
    defs: dict[str, dict] = {}
    roots: list[tuple[str, dict]] = []
    for model in MODELS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        defs.update(schema.pop("$defs", {}))
        roots.append((model.__name__, schema))

    out.append("// ---- nested types ---------------------------------------------")
    for name in sorted(defs):
        node = defs[name]
        if "enum" in node:
            continue  # already emitted above, or a python-only enum
        if any(name == root for root, _ in roots):
            continue  # a top-level model referenced by another; emit it once below
        out.extend(emit_interface(name, node))
        out.append("")

    out.append("// ---- models ---------------------------------------------------")
    for name, schema in roots:
        out.extend(emit_interface(name, schema))
        out.append("")

    out.append("// ---- convenience ----------------------------------------------")
    out.append("/** One line of out/events.ndjson. */")
    out.append("export type EventLine = Event;")
    out.append("/** The whole of out/results.json. */")
    out.append("export type Results = Forecast;")
    out.append("")

    return "\n".join(out)


def main() -> None:
    sys.stdout.write(build())


if __name__ == "__main__":
    main()
