"""pydantic schemas -> ui/lib/types.ts. Run via `make types`.

Stops the pipeline and the frontend drifting. They otherwise will, and you find
out at 16:00 on the day when a field renamed three days earlier silently renders
as undefined.
"""

from __future__ import annotations

import json
import sys

from forecaster import schemas

MODELS = [
    schemas.Source, schemas.Claim, schemas.Consensus, schemas.Guidance,
    schemas.LandingDistribution, schemas.LensOutput, schemas.Distribution,
    schemas.LambdaDecision, schemas.Forecast, schemas.Event,
]


def main() -> None:
    out = [
        "// GENERATED by `make types` from src/forecaster/schemas.py",
        "// Do not edit. Change the pydantic model and regenerate.",
        "",
    ]
    for enum in (schemas.Basis, schemas.SourceKind, schemas.LensName,
                 schemas.LambdaPreset, schemas.EventType):
        members = " | ".join(f'"{m.value}"' for m in enum)
        out.append(f"export type {enum.__name__} = {members};")
    out.append("")
    for model in MODELS:
        schema = model.model_json_schema()
        out.append(f"// {model.__name__}")
        out.append(f"export type {model.__name__}JsonSchema = {json.dumps(schema)};")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
